apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  ports:
    - port: 5432
      name: broker
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-entrypoint
data:
  pg.sql: |
    CREATE TABLAE test ( id integer );

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: app
          image: postgres:14.5
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: config-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: config-volume
          configMap:
            name: pg-entrypoint
            items:
              - key: pg.sql
                path: pg.sql
