apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  ports:
    - port: 9411
      name: broker
      protocol: TCP
      targetPort: 9411
  selector:
    app: zipkin
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      name: zipkin
      labels:
        app: zipkin
    spec:
      containers:
        - name: app
          image: openzipkin/zipkin:latest-arm64
