apiVersion: v1
kind: Service
metadata:
  name: spring-gateway
  labels:
    app: spring-gateway
spec:
  ports:
    - name: http
      port: 30080
      nodePort: 30080
    - name: debug
      port: 30050
      nodePort: 30050
  selector:
    app: spring-gateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-gateway
  labels:
    app: spring-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-gateway
  template:
    metadata:
      labels:
        app: spring-gateway
    spec:
      containers:
        - name: java-app
          image: ppojin/gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 30080
          env:
            - name: SERVER_PORT
              value: "30080"
            - name: KEYCLOAK_URI
              value: http://keycloak:8080
            - name: HTTPBIN_URI
              value: http://httpbin-lb.default.svc:8088
          resources:
            # requests:
            #   memory: "256Mi"
            #   cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
